---
- name: Ensure Credentials Directory Exists
  ansible.builtin.file:
    path: "{{ mariadb_credentials_save_path }}"
    state: directory
    mode: "0700"
  delegate_to: localhost
  become: false

- name: Save MariaDB Root Credentials
  ansible.builtin.template:
    src: credentials.yml.j2
    dest: "{{ mariadb_credentials_save_path }}/{{ inventory_hostname }}.yml"
    mode: "0600"
  delegate_to: localhost
  become: false
