---
- name: Set MariaDB Root Password
  community.mysql.mysql_user:
    name: root
    host: localhost
    password: "{{ mariadb_root_password }}"
    login_unix_socket: "{{ mariadb_socket }}"
    state: present

- name: Create MariaDB Client Configuration for Root
  ansible.builtin.template:
    src: root_my.cnf.j2
    dest: /root/.my.cnf
    owner: root
    group: root
    mode: "0600"

- name: Remove Anonymous Users
  community.mysql.mysql_user:
    name: ""
    host_all: true
    login_unix_socket: "{{ mariadb_socket }}"
    state: absent

- name: Remove Test Database
  community.mysql.mysql_db:
    name: test
    login_unix_socket: "{{ mariadb_socket }}"
    state: absent

- name: Disallow Root Login Remotely
  community.mysql.mysql_user:
    name: root
    host: "{{ item }}"
    login_unix_socket: "{{ mariadb_socket }}"
    state: absent
  loop:
    - "{{ ansible_facts['hostname'] }}"
    - "{{ ansible_facts['fqdn'] }}"
  when: item != 'localhost'
  failed_when: false
